export const codevilles = [
    {ville: 'Valmorel', insee: 73024 }, //SAVOIE
    {ville: 'Brides-les-Bains', insee: 73057 }, 
    {ville: 'Champagny-en-Vanoise', insee: 73071 }, 
    {ville: 'Crest-Voland', insee: 73094 }, 
    {ville: 'Flumet', insee: 73114 }, 
    {ville: 'La Rosière', insee: 73176 }, 
    {ville: 'Les Saisies', insee: 73620 }, 
    {ville: 'Bellentre', insee: 73038 }, 
    {ville: 'Notre Dame de Bellecombe', insee: 73186 }, 
    {ville: 'St François Longchamp', insee: 73235 }, 
    {ville: 'Saint-Martin-de-Belleville', insee: 73257 }, 
    {ville: 'Valloire', insee: 73306 }, 
    {ville: 'Valmeinier', insee: 73307 }, 
    {ville: 'Villaroger', insee: 73323 }, 
    {ville: 'La Plagne', insee: 73150 },
    {ville: 'Courchevel', insee: 73227},
    {ville: 'Les Arcs', insee: 83004},
    {ville: 'Les Menuires', insee: 73257},
    {ville: 'Méribel', insee: 73015},
    {ville: 'Tignes', insee: 73296},
    {ville: 'Val Cenis', insee: 73290}, 
    {ville: "Val d'Isère", insee: 73304}, //Isère
    {ville: "Val Thorens", insee: 73928},
    {ville: "Alpe d'Huez", insee: 38191},
    {ville: "Chamrousse", insee: 38567},
    {ville: "Les 2 Alpes", insee: 38253},
    {ville: "Autrans", insee: 38021},
    {ville: "Villard-De-Lans", insee: 38548},
    {ville: "Lans en Vercors", insee: 38205},
    {ville: "St Pierre de Chartreuse", insee: 38442},
    {ville: "Alpe du Grand Serre", insee: 26143},
    {ville: "Corrençon-En-Vercors", insee: 38129},
    {ville: "Oz en Oisans", insee: 38289},
    {ville: "Vaujany", insee: 38527},
    {ville: "Les Orres", insee: '05098'}, // hautes-Alpes
    {ville: "Montgenèvres", insee: '05085'},
    {ville: "Puy-Saint-Vincent", insee: '05110'},
    {ville: "Risoul", insee: '05119'},
    {ville: "Ancelle", insee: '05004'},
    {ville: "Orcières", insee: '05096'},
    {ville: "Serre Chevalier", insee: '05166'},
    {ville: "Vars", insee: '05177'},
    {ville: "Le Dévoluy", insee: '05139'},
    {ville: "Saint-Véran", insee: '05157'},
    {ville: "Vallouise", insee: '05101'},
    {ville: "Réallon", insee: '05114'}, 
    {ville: "Avoriaz", insee: 74950}, // Haute-Savoie
    {ville: "Chamonix", insee: 74056},
    {ville: "La Clusaz", insee: 74080},
    {ville: "Megève", insee: 74173},
    {ville: "Morzine", insee: 74191},
    {ville: "Samoëns", insee: 74258},
    {ville: "Châtel", insee: 74063}, 
    {ville: "Flaine", insee: 74951}, 
    {ville: "Le Grand-Bornand", insee: 74136}, 
    {ville: "Les Contamines-Montjoie", insee: 74085}, 
    {ville: "Les Gets", insee: 74134}, 
    {ville: "Morillon", insee: 74190}, 
    {ville: "Praz sur Arly", insee: 74215}, 
    {ville: "Saint-Gervais-Les-Bains", insee: 74236}, 
    {ville: "Sixt-Fer-à-Cheval", insee: 74273}, 
    {ville: "Pra Loup", insee: '04923'}, // Alpes de Haute-Provence
    {ville: "Montclar", insee: '04126'}, 
    {ville: "Foux d'Allos (La)", insee: '04921'}, 
    {ville: "Allos", insee: '04006'}, 
    {ville: "Auron", insee: '06901'}, // Alpes-Maritimes
    {ville: "Beuil", insee: '06016'}, 
    {ville: "Isola", insee: '06073'}, 
    {ville: "Roubion", insee: '06110'}, 
    {ville: "Valberg", insee: '06906'}, 
    {ville: "Font Romeu Odeillo Via", insee: 66124}, // Pyrénées
    {ville: "Les Angles", insee: 30011}, 
    {ville: "Ax-Les-Thermes", insee: '09032'}, 
    {ville: "Cauterets", insee: 65138}, 
    {ville: "Luz Saint-Sauveur", insee: 65295}, 
    {ville: "Piau Engaly", insee: 65017}, 
    {ville: "Saint Lary Soulan", insee: 65388}, 
    {ville: "Gourette", insee: 64904}, 
    {ville: "Gérardmer", insee: 88196}, // Les Vosges
    {ville: "La Bresse", insee: 88075}, 
    {ville: "Saint Maurice sur Moselle", insee: 88426}, 
    {ville: "Ventron", insee: 88500}, 
    {ville: "Lélex", insee: '01210'}, // Jura
    {ville: "Les Rousses", insee: 39470}, 
    {ville: "Métabief", insee: 25380}, 
    {ville: "Fourgs (Les)", insee: 25254}, 
    {ville: "Foncine-le-Haut", insee: 39228}, 
    {ville: "Hauteville Lompnes", insee: '01185'}, 
];

export const listevilles = [ 'Valmorel', 'La Plagne', 'Courchevel', 'Les Arcs', 'Les Menuires', 'Méribel', 'Tignes', 'Val Cenis', "Val d'Isère", "Val Thorens", "Alpe d'Huez", "Chamrousse", "Les 2 Alpes", 'Autrans', 'Villard-De-Lans', 'Lans en Vercors', 'St Pierre de Chartreuse', "Les Orres", "Montgenèvres", "Puy-Saint-Vincent", "Risoul", "Serre Chevalier", "Vars", "Avoriaz", "Chamonix", "La Clusaz", "Megève", "Morzine", "Samoëns", "Brides-les-Bains", "Champagny-en-Vanoise", "Crest-Voland", "Flumet", "La Rosière", "Les Saisies", "Bellentre", "Notre Dame de Bellecombe", "St François Longchamp", "Saint-Martin-de-Belleville", "Valloire", "Valmeinier", "Villaroger", "Alpe du Grand Serre", "Corrençon-En-Vercors", "Oz en Oisans", "Vaujany", "Ancelle", "Orcières", "Le Dévoluy", "Saint-Véran", "Vallouise", "Réallon", "Châtel", "Flaine", "Le Grand-Bornand", "Les Contamines-Montjoie", "Les Gets", "Morillon", "Praz sur Arly", "Saint-Gervais-Les-Bains", "Sixt-Fer-à-Cheval", "Pra Loup", "Montclar", "Foux d'Allos (La)", "Allos", "Auron", "Beuil", "Isola", "Roubion", "Valberg", "Font Romeu Odeillo Via", "Les Angles", "Ax-Les-Thermes", "Cauterets", "Luz Saint-Sauveur", "Piau Engaly", "Saint Lary Soulan", "Gourette", "Gérardmer", "La Bresse", "Saint Maurice sur Moselle", "Ventron", "Lélex", "Les Rousses", "Métabief", "Fourgs (Les)", "Foncine-le-Haut", "Hauteville Lompnes"];
